/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const LanguageSummary = IDL.Record({
  'language' : IDL.Text,
  'savedAt' : IDL.Int,
});
export const CodeSnippet = IDL.Record({
  'code' : IDL.Text,
  'language' : IDL.Text,
  'savedAt' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteCode' : IDL.Func([IDL.Text], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listLanguages' : IDL.Func([], [IDL.Vec(LanguageSummary)], ['query']),
  'loadCode' : IDL.Func([IDL.Text], [IDL.Opt(CodeSnippet)], ['query']),
  'saveCode' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const LanguageSummary = IDL.Record({
    'language' : IDL.Text,
    'savedAt' : IDL.Int,
  });
  const CodeSnippet = IDL.Record({
    'code' : IDL.Text,
    'language' : IDL.Text,
    'savedAt' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteCode' : IDL.Func([IDL.Text], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listLanguages' : IDL.Func([], [IDL.Vec(LanguageSummary)], ['query']),
    'loadCode' : IDL.Func([IDL.Text], [IDL.Opt(CodeSnippet)], ['query']),
    'saveCode' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };